# Generated by Django 6.1 on 2026-08-12 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='كۇرس ئىسمى')),
                ('badge', models.CharField(choices=[('تور + سىنىپ', 'تور + سىنىپ'), ('بالىلار', 'بالىلار'), ('تېخنىكا', 'تېخنىكا'), ('ئىلمىي ساۋات', 'ئىلمىي ساۋات'), ('كۆپ تىللىق', 'كۆپ تىللىق'), ('مەخسۇس سىنىپ', 'مەخسۇس سىنىپ')], max_length=50, verbose_name='بەلگە')),
                ('description', models.TextField(verbose_name='چۈشەندۈرۈش')),
                ('textbook', models.CharField(blank=True, max_length=200, verbose_name='ئاساسلىق دەرسلىك')),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='سەۋىيە تەلەپلىرى')),
                ('teaching_method', models.CharField(blank=True, max_length=200, verbose_name='ئوقۇتۇش شەكلى')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='مەسئۇل ئوقۇتقۇچى')),
                ('age_group', models.CharField(blank=True, max_length=100, verbose_name='مۇۋاپىق ياش')),
                ('special_features', models.CharField(blank=True, max_length=300, verbose_name='ئالاھىدىلىكى')),
                ('is_active', models.BooleanField(default=True, verbose_name='ئاكتىپمۇ؟')),
                ('order', models.IntegerField(default=0, verbose_name='تەرتىپ نومۇرى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'كۇرس',
                'verbose_name_plural': 'كۇرسىلار',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='پىكىر')),
                ('author', models.CharField(max_length=100, verbose_name='ئاپتور')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'پىكىر',
                'verbose_name_plural': 'پىكىرلەر',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ئىسمى')),
                ('role', models.CharField(max_length=100, verbose_name='ۋەزىپىسى')),
                ('description', models.TextField(verbose_name='چۈشەندۈرۈش')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='رەسىم')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='ئېموجى')),
                ('order', models.IntegerField(default=0, verbose_name='تەرتىپ نومۇرى')),
            ],
            options={
                'verbose_name': 'ئوقۇتقۇچى',
                'verbose_name_plural': 'ئوقۇتقۇچىلار',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ئىسمى فامىلىسى'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تېلېفون نومۇرى'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='تېلېگرامما ئادرېسى'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'كۈتۈلۈۋاتىدۇ'), ('approved', 'تەستىقلاندى'), ('rejected', 'رەت قىلىندى')], default='pending', max_length=20, verbose_name='ھالەت')),
                ('message', models.TextField(blank=True, verbose_name='ئۇچۇر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='كۇرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ئىشلەتكۈچى')),
            ],
            options={
                'verbose_name': 'تىزىملىتىش',
                'verbose_name_plural': 'تىزىملىتىشلار',
            },
        ),
    ]
