# Generated by Django 6.1 on 2026-08-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_review_teacher_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ماۋزۇ')),
                ('description', models.TextField(verbose_name='چۈشەندۈرۈش')),
                ('image', models.ImageField(blank=True, null=True, upload_to='works/', verbose_name='رەسىم')),
                ('order', models.IntegerField(default=0, verbose_name='تەرتىپ نومۇرى')),
            ],
            options={
                'verbose_name': 'خىزمەت',
                'verbose_name_plural': 'قىلغان خىزمەتلەر',
                'ordering': ['order'],
            },
        ),
    ]
