# Generated by Django 6.1 on 2026-08-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='رەسىم'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='ۋاقتى'),
        ),
        migrations.AddField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='تولۇق چۈشەندۈرۈش'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(default=20, verbose_name='ئەڭ كۆپ ئوقۇغۇچى'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='باھاسى'),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, verbose_name='دەرس ۋاقتى'),
        ),
    ]
