# Generated by Django 6.1 on 2026-08-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_cover_image_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
