# Generated by Django 6.1 on 2026-08-12 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='ئوقۇتقۇچى (User)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'ئوقۇغۇچى'), ('teacher', 'ئوقۇتقۇچى'), ('admin', 'باشقۇرغۇچى')], default='student', max_length=20, verbose_name='رولى'),
        ),
    ]
