# Generated by Django 6.1 on 2026-08-13 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_teacher_user_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'تىزىملىتىش', 'verbose_name_plural': 'تىزىملىتىشلار'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order'], 'verbose_name': 'ئوقۇتقۇچى (Team)', 'verbose_name_plural': 'ئوقۇتقۇچىلار قوشۇنى'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='teacher_note',
            field=models.TextField(blank=True, verbose_name='ئوقۇتقۇچى ئىزاھى'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, verbose_name='مەسئۇل ئوقۇتقۇچى (ئىسىم)'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='كۇرس'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='message',
            field=models.TextField(blank=True, verbose_name='ئوقۇغۇچى ئۇچۇرى'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='ئوقۇغۇچى'),
        ),
    ]
