# Generated by Django 6.1 on 2026-08-14 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_enrollment_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_user',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.teacher', verbose_name='مەسئۇل ئۇستاز'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='كىرىش ھېساباتى (User)'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teacher_note',
            field=models.TextField(blank=True, verbose_name='ئۇستاز ئىزاھى'),
        ),
    ]
