# Generated by Django 6.1 on 2026-08-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_teacher_remove_course_teacher_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='emoji',
            field=models.CharField(blank=True, max_length=50, verbose_name='ئىموجى/Icon'),
        ),
    ]
