# Generated by Django 6.1 on 2026-08-14 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('approved', 'تەستىقلاندى'), ('rejected', 'رەت قىلىندى'), ('message', 'ئۇچۇر'), ('system', 'سىستېما')], max_length=20, verbose_name='تىپى')),
                ('title', models.CharField(max_length=200, verbose_name='ماۋزۇ')),
                ('message', models.TextField(verbose_name='ئۇچۇر')),
                ('is_read', models.BooleanField(default=False, verbose_name='ئوقۇلدى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='كۇرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ئىشلەتكۈچى')),
            ],
            options={
                'verbose_name': 'ئۇقتۇرۇش',
                'verbose_name_plural': 'ئۇقتۇرۇشلار',
                'ordering': ['-created_at'],
            },
        ),
    ]
