# Generated by Django 6.1 on 2026-08-14 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='ماۋزۇ')),
                ('message', models.TextField(verbose_name='ئۇچۇر')),
                ('is_read', models.BooleanField(default=False, verbose_name='ئوقۇلدى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='مۇناسىۋەتلىك كۇرس')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='قوبۇل قىلغۇچى')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='يوللىغۇچى')),
            ],
            options={
                'verbose_name': 'ئۇچۇر',
                'verbose_name_plural': 'ئۇچۇرلار',
                'ordering': ['-created_at'],
            },
        ),
    ]
