# Generated by Django 6.1 on 2026-08-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Edraak Education', max_length=200, verbose_name='توربەت ئىسمى (ئېنگلىزچە)')),
                ('site_name_ug', models.CharField(default='ئىدراك مائارىپى', max_length=200, verbose_name='توربەت ئىسمى (ئۇيغۇرچە)')),
                ('tagline', models.CharField(blank=True, default='Guiding the Future | كەلگۈسىگە يېتەكلەش', max_length=300, verbose_name='شۇئار')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو رەسىمى')),
                ('about_title_ug', models.CharField(default='ئىدراك مائارىپى غايىسى', max_length=200, verbose_name='بىز ھەققىدە ماۋزۇسى (ئۇيغۇرچە)')),
                ('about_text_ug', models.TextField(blank=True, verbose_name='بىز ھەققىدە مەزمۇنى (ئۇيغۇرچە)')),
                ('about_title_en', models.CharField(default='Our Mission', max_length=200, verbose_name='بىز ھەققىدە ماۋزۇسى (ئېنگلىزچە)')),
                ('about_text_en', models.TextField(blank=True, verbose_name='بىز ھەققىدە مەزمۇنى (ئېنگلىزچە)')),
                ('whatsapp', models.CharField(blank=True, default='905444362947', max_length=50, verbose_name='WhatsApp نومۇرى (پەقەت سان)')),
                ('telegram', models.CharField(blank=True, default='salman_muallim', max_length=100, verbose_name='Telegram ئادرېسى')),
                ('email', models.EmailField(blank=True, default='salmanuyghur3@gmail.com', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='+90 544 436 29 47', max_length=50, verbose_name='تېلېفون نومۇرى (كۆرۈنۈش)')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='ئادرېس')),
                ('footer_text', models.CharField(blank=True, default='© 2026 Edraak Education. All rights reserved.', max_length=300, verbose_name='Footer تېكىستى')),
            ],
            options={
                'verbose_name': 'توربەت تەڭشەكلىرى',
                'verbose_name_plural': 'توربەت تەڭشەكلىرى',
            },
        ),
    ]
