# Generated by Django 6.1 on 2026-08-16 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ماۋزۇ')),
                ('material_type', models.CharField(choices=[('pdf', '📄 PDF ھۆججەت'), ('video', '🎬 Video'), ('link', '🔗 ئۇلىنىش'), ('doc', '📝 ھۆججەت'), ('other', '📦 باشقا')], default='pdf', max_length=20, verbose_name='تىپى')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='ھۆججەت (PDF/Doc)')),
                ('url', models.URLField(blank=True, verbose_name='ئۇلىنىش (Video/Web)')),
                ('description', models.TextField(blank=True, verbose_name='چۈشەندۈرۈش')),
                ('order', models.IntegerField(default=0, verbose_name='تەرتىپ نومۇرى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='كۇرس')),
            ],
            options={
                'verbose_name': 'كۇرس ماتېرىيالى',
                'verbose_name_plural': 'كۇرس ماتېرىياللىرى',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
