# Generated by Django 6.1 on 2026-08-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_coursematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='ئۇلىنىش (Video/Web)'),
        ),
    ]
