# Generated by Django 6.1 on 2026-08-16 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_coursematerial_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='دەرس ماۋزۇسى')),
                ('day_of_week', models.IntegerField(choices=[(0, 'يەكشەنبە'), (1, 'دۈشەنبە'), (2, 'سەيشەنبە'), (3, 'چارشەنبە'), (4, 'پەيشەنبە'), (5, 'جۈمە'), (6, 'شەنبە')], verbose_name='ھەپتە كۈنى')),
                ('start_time', models.TimeField(verbose_name='باشلىنىش ۋاقتى')),
                ('end_time', models.TimeField(verbose_name='ئاخىرلىشىش ۋاقتى')),
                ('description', models.TextField(blank=True, verbose_name='چۈشەندۈرۈش')),
                ('online_link', models.URLField(blank=True, verbose_name='تور دەرس ئۇلىنىشى (Zoom/Meet)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='سىنىپ ئورنى')),
                ('is_active', models.BooleanField(default=True, verbose_name='ئاكتىپمۇ؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='كۇرس')),
            ],
            options={
                'verbose_name': 'دەرس جەدۋىلى',
                'verbose_name_plural': 'دەرس جەدۋىللىرى',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
