# Generated by Django 6.1 on 2026-08-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='سوئال')),
                ('answer', models.TextField(verbose_name='جاۋاب')),
                ('category', models.CharField(choices=[('registration', 'تىزىملىتىش'), ('courses', 'كۇرسىلار'), ('payment', 'تۆلەم'), ('schedule', 'دەرس جەدۋىلى'), ('other', 'باشقا')], default='other', max_length=50, verbose_name='تۈر')),
                ('order', models.IntegerField(default=0, verbose_name='تەرتىپ نومۇرى')),
                ('is_active', models.BooleanField(default=True, verbose_name='ئاكتىپمۇ؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ سوئال-جاۋابلار',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
