# Generated by Django 6.1 on 2026-08-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='ئېلان ماۋزۇسى')),
                ('content', models.TextField(verbose_name='ئېلان مەزمۇنى')),
                ('announcement_type', models.CharField(choices=[('info', '📢 ئادەتتىكى ئېلان'), ('success', '🎉 مۇۋەپپەقىيەت'), ('warning', '⚠️ ئاگاھلاندۇرۇش'), ('important', '🔴 مۇھىم ئېلان')], default='info', max_length=20, verbose_name='ئېلان تىپى')),
                ('target_audience', models.CharField(choices=[('all', 'ھەممىسى'), ('students', 'پەقەت ئوقۇغۇچىلار'), ('teachers', 'پەقەت ئوقۇتقۇچىلار')], default='all', max_length=20, verbose_name='نىشان ئوقۇرمەن')),
                ('is_active', models.BooleanField(default=True, verbose_name='ئاكتىپمۇ؟')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='باشلىنىش ۋاقتى')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='ئاخىرلىشىش ۋاقتى (ئىختىيارى)')),
                ('link_url', models.URLField(blank=True, verbose_name='ئۇلىنىش (ئىختىيارى)')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='ئۇلىنىش تېكىستى')),
                ('order', models.IntegerField(default=0, verbose_name='تەرتىپ نومۇرى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ئېلان',
                'verbose_name_plural': 'ئېلانلار',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
