# Generated by Django 6.1 on 2026-08-21 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='دەرس ۋاقتى')),
                ('topic', models.CharField(blank=True, max_length=300, verbose_name='دەرس تېمىسى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL, verbose_name='قۇرغۇچى')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.lesson', verbose_name='دەرس')),
            ],
            options={
                'verbose_name': 'ھازىرلىق Session',
                'verbose_name_plural': 'ھازىرلىق Session لار',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='ھازىرلىق ۋاقتى')),
                ('status', models.CharField(choices=[('present', 'ھازىر'), ('absent', 'يوق'), ('late', 'كېچىكىپ كەلدى'), ('excused', 'سەۋەبلىك يوق')], default='present', max_length=20, verbose_name='ھالەت')),
                ('note', models.TextField(blank=True, verbose_name='ئىزاھات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.lesson', verbose_name='دەرس')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='بەلگىلىگۈچى')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='ئوقۇغۇچى')),
            ],
            options={
                'verbose_name': 'ھازىرلىق',
                'verbose_name_plural': 'ھازىرلىق خاتىرىسى',
                'ordering': ['-attendance_date'],
                'unique_together': {('lesson', 'student', 'attendance_date')},
            },
        ),
    ]
