# Generated by Django 6.1 on 2026-08-21 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_attendancesession_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ئىمتىھان ماۋزۇسى')),
                ('exam_type', models.CharField(choices=[('written', '📝 يېزىقچە'), ('oral', '🗣️ ئاغزاكى'), ('practical', '🛠️ ئەمەلىي'), ('quiz', '❓ تېز سوئال'), ('midterm', '📘 ئارىلىق ئىمتىھان'), ('final', '📕 ئاخىرقى ئىمتىھان')], default='written', max_length=20, verbose_name='ئىمتىھان تىپى')),
                ('total_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='ئومۇمىي نومۇر')),
                ('exam_date', models.DateField(verbose_name='ئىمتىھان ۋاقتى')),
                ('description', models.TextField(blank=True, verbose_name='چۈشەندۈرۈش')),
                ('is_published', models.BooleanField(default=False, verbose_name='ئېلان قىلىندىمۇ؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='كۇرس')),
            ],
            options={
                'verbose_name': 'ئىمتىھان',
                'verbose_name_plural': 'ئىمتىھانلار',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نومۇر')),
                ('note', models.TextField(blank=True, verbose_name='ئوقۇتقۇچى ئىزاھى')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.exam', verbose_name='ئىمتىھان')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_exams', to=settings.AUTH_USER_MODEL, verbose_name='باھالىغۇچى')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL, verbose_name='ئوقۇغۇچى')),
            ],
            options={
                'verbose_name': 'ئىمتىھان نەتىجىسى',
                'verbose_name_plural': 'ئىمتىھان نەتىجىلىرى',
                'ordering': ['-score'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
