# Generated by Django 6.1 on 2026-08-27 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_exam_examresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='گۇۋاھنامە نومۇرى')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='بېرىلغان ۋاقتى')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='كۇرس')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='بەرگۈچى')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='ئوقۇغۇچى')),
            ],
            options={
                'verbose_name': 'گۇۋاھنامە',
                'verbose_name_plural': 'گۇۋاھنامىلەر',
                'ordering': ['-issue_date'],
            },
        ),
    ]
