# Generated by Django 6.1 on 2026-08-27 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='باھا (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='ئىنكاس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='يېزىلغان ۋاقتى')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='يېڭىلانغان ۋاقتى')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course', verbose_name='كۇرس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL, verbose_name='ئوقۇغۇچى')),
            ],
            options={
                'verbose_name': 'كۇرس باھاسى',
                'verbose_name_plural': 'كۇرس باھالىرى',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'student')},
            },
        ),
    ]
